services:
  # Our PostgreSQL database
  db:
    #Using the latest PostgreSQL image
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: changemeinprod!

  # Database management interface
  adminer:
    image: adminer:latest
    ports:
      - "8888:8080"